#!/usr/bin/env python

products = {
    "olma": 9990,
    "banan": 23499,
    "mandarin": 43090,
    "ananas": 43400,
    "apelsin": 23000
}

savatcha = {
    "olma": 0,
    "banan": 0,
    "mandarin": 0,
    "ananas": 0,
    "apelsin": 0
}

print("Python marketga xush kelibsiz")
print("Mavjud maxsulotlar :")

for maxsulot, narx in products.items():
    print(maxsulot, ",", narx)

while True:
    narsa = input("Maxsulatni tanlang : ").lower()

    if narsa == "exit":
        break

    if narsa in products:
        savatcha[narsa] += 1
        print(narsa, "[+]", narsa, "Savatga qoshildi!")
    else:
        print("[-] Bunday maxsulot mavjud emas!")

umumiy_narx = 0

print("Siz tanlagan Maxsulotlar:")

for maxsulot, son in savatcha.items():
    umumiy_narx += products[maxsulot] * son
    if son != 0:
        print(maxsulot, "[", son, "kg ]", products[maxsulot] * son, "sum")

print("Umumiy narx :", umumiy_narx, "sum")
