#!/usr/bin/python

def appendFile(file):
    f = open(file, "a")
    data = input("Data: ")  # сюда пишем что добавить
    data = f"\n{data}"
    f.write(data)
    print("Data successfully appended.")
    f.close()
    readFile(file)

def readFile(file):
    f = open(file, "r")
    data = f.read()
    print(f"----------{file}----------")
    print(data)
    f.close()

def writeFile(file):
    f = open(file, "w")  # все удалит и заново запишет
    data = input("Data: ")
    f.write(data)
    print("Data successfully written.")
    f.close()
    readFile(file)

def main():
    print("\n---------- File Management Program ---------------\n")
    fayl = input("File: ")  # имя файла
    mode = input("Mode (a - append, r - read, w - write): ")

    if mode == "a":
        appendFile(fayl)
    elif mode == "r":
        readFile(fayl)
    elif mode == "w":
        writeFile(fayl)
    else:
        print("Invalid Option")  # не то выбрал

while True:
    main()
