#!/usr/bin/python

fayl = input("Fayl nomini kiriting: ")  # тут вводим имя файла

device = input("Fayl bilan qanday ish amalga oshirmoqchisiz (a, r, w): ")  # режим типа (читать, писать, добаить)

if device == "a":
    f = open(fayl, device)
    text = input("Faylga yana nima qoshmoqchisiz: ")
    text = f"\n{text}"
    f.write(text)

elif device == "r":
    f = open(fayl, device)
    text1 = input("[1] Qatorlarni alohida chiqarasizmi yoki [2] butun faylni oqish kerakmi? ")

    if text1 == "1":
        i = 1
        for qator in f.readlines():
            print(i, qator)
            i += 1

    elif text1 == "2":
        data = f.read()
        print(data)

    else:
        print("Notogri variant tanlandi!")  

elif device == "w":
    f = open(fayl, device)
    text2 = input("Faylga nima yozmoqchisiz (Bu usul fayl ichidagi malumotlarni ochirib yuboradi): ")
    f.write(text2)

else:
    print("Notogri variant tanlandi!")  # фигню ввел, заново надо

f.close()  # закрыть, а то не сохранится
